const db = require('./db');

(async function() {
	const [ direction ] = await db.directions.insert([
		{
			code: '56.04.02',
			note: 'Тестовый пример направления подготовки',
			complexity: 120,
			education_duration: 2,
			name: 'Управление воинскими частями и соединениями',
			qualification: 'магистр',
		},
	]);

	const direction_id = direction._id;

	const competencies = await db.competencies.insert([
		{
			type: 'общекультурные компетенции',
			activity_kind: null,
			description: 'Готовность действовать в нестандартных ситуациях, нести социальную и этическую ответственность за принятые решения',
			code: 'ОК-1',
			direction_id,
			common: true,
		},
		{
			type: 'общекультурные компетенции',
			activity_kind: null,
			description: 'Способность совершенствовать и применять гуманитарные, языковые и социально-экономические знания в сфере профессиональной деятельности',
			code: 'ОК-2',
			direction_id,
			common: true,
		},
		{
			type: 'общекультурные компетенции',
			activity_kind: null,
			description: 'Способность анализировать и оценивать современные общественно-политические явления и социальные процессы в Российской Федерации и за рубежом',
			code: 'ОК-3',
			direction_id,
			common: true,
		},
		{
			type: 'общекультурные компетенции',
			activity_kind: null,
			description: 'Способность к физическому самосовершенствованию',
			code: 'ОК-4',
			direction_id,
			common: true,
		},
		{
			type: 'общепрофессиональные компетенции',
			activity_kind: null,
			description: 'Способность анализировать и оценивать современную военно-политическую обстановку в стране и в мире, социальные процессы в Вооружённых Силах Российской Федерации',
			code: 'ОПК-1',
			direction_id,
			common: true,
		},
		{
			type: 'общепрофессиональные компетенции',
			activity_kind: null,
			description: 'Способность самостоятельно приобретать и использовать новые знания и умения в сфере профессиональной деятельности  и в новых областях знаний, непосредственно не связанных со сферой профессиональной деятельности',
			code: 'ОПК-2',
			direction_id,
			common: true,
		},
		{
			type: 'общепрофессиональные компетенции',
			activity_kind: null,
			description: 'Способность вырабатывать новые идеи, применять количественные и качественные методы для анализа, обоснования и оценки управленческих решений в профессиональной деятельности, в том числе и в условиях неопределенности, принимать ответственность за свои решения',
			code: 'ОПК-3',
			direction_id,
			common: true,
		},
		{
			type: 'общепрофессиональные компетенции',
			activity_kind: null,
			description: 'Способность к профессиональному и служебному росту, изменению при необходимости вида и профиля своей профессиональной (служебной) деятельности',
			code: 'ОПК-4',
			direction_id,
			common: true,
		},
		{
			type: 'общепрофессиональные компетенции',
			activity_kind: null,
			description: 'Способность работать самостоятельно и в коллективе, осуществлять руководство, подчиняться и сотрудничать с учетом правовых, этических и нравственных норм, установленных прав и обязанностей, оказывать личным примером позитивное воздействие на окружающих',
			code: 'ОПК-5',
			direction_id,
			common: true,
		},
		{
			type: 'общепрофессиональные компетенции',
			activity_kind: null,
			description: 'Способность применять современные информационные технологии в сфере профессиональной деятельности',
			code: 'ОПК-6',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность осуществлять планирование, организацию, руководство и контроль при управлении воинской частью, соединением (войсками, силами)',
			code: 'ПК-1',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность управлять тактическими (боевыми) действиями и повседневной деятельностью воинской части, соединения (войск, сил) в различных условиях обстановки',
			code: 'ПК-2',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Cпособность управлять обеспечением тактических (боевых) действий и повседневной деятельности воинской части, соединения (войск, сил) в различных условиях обстановки',
			code: 'ПК-3',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность принимать управленческие решения в различных условиях обстановки',
			code: 'ПК-4',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность управлять работой органов управления воинской части, соединения (войск, сил) в различных условиях обстановки',
			code: 'ПК-5',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность управлять морально-психологическим состоянием личного состава в интересах выполнения стоящих задач, руководить военно-педагогическим процессом в воинской части, соединении (войск, сил)',
			code: 'ПК-6',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность управлять научно-исследовательской, изобретательской и рационализаторской деятельностью в воинской части, соединении (войск, сил)',
			code: 'ПК-7',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность разрабатывать самостоятельно и в составе коллектива документы, регламентирующие деятельность воинской части, соединения (войск, сил) в различных условиях обстановки',
			code: 'ПК-8',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-техническая деятельность',
			description: 'Способность обеспечить требуемый уровень готовности вооружения и военной техники',
			code: 'ПК-9',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-техническая деятельность',
			description: 'Способность эффективно использовать боевые, эксплуатационные свойства и технические возможности вооружения и военной техники в различных условиях боевой обстановки',
			code: 'ПК-10',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'научно-исследовательская деятельность',
			description: 'Способность организовывать самостоятельную и коллективную научно-исследовательскую работу в рамках профессиональной деятельности, разрабатывать планы и программы проведения научных исследований, разрабатывать задания для исполнителей',
			code: 'ПК-11',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'научно-исследовательская деятельность',
			description: 'Готовность к поиску, обработке, анализу и систематизации научной информации по теме исследования, выбору методик и средств решения задачи',
			code: 'ПК-12',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'научно-исследовательская деятельность',
			description: 'Способность использовать научные методы и современные достижения науки для обоснования решений, принимаемых в профессиональной деятельности',
			code: 'ПК-13',
			direction_id,
			common: true,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность управлять подготовкой и боевыми действиями (боевым применением) воинской части, соединения, объединения ПВО в различных условиях обстановки',
			code: 'ВПК.ПК-14',
			direction_id,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность управлять повседневной деятельностью воинской части, соединения ПВО в различных условиях обстановки',
			code: 'ВПК.ПК-15',
			direction_id,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность организовывать и управлять всеми видами обеспечения воинской части, соединения, объединения ПВО в различных условиях обстановки',
			code: 'ВПК.ПК-16',
			direction_id,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-управленческая деятельность',
			description: 'Способность логически верно, аргументированно и ясно строить устную и письменную речь на русском языке в условиях учебно-профессионального общения',
			code: 'ВПК.ПК-17',
			direction_id,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'военно-техническая деятельность',
			description: 'Способность обеспечивать требуемый уровень готовности ВВСТ и эффективно использовать боевые, эксплуатационные свойства и технические возможности ВВСТ в повседневной и боевой деятельностивоинской части, соединения, объединения ПВО',
			code: 'ВПК.ПК-18',
			direction_id,
		},
		{
			type: 'профессиональные компетенции',
			activity_kind: 'научно-исследовательская деятельность',
			description: 'Способность применять информационно-коммуникационные технологии при организации и проведении военно-научных исследований',
			code: 'ВПК.ПК-19',
			direction_id,
		},
	]);

	const competenciesIds = [];

	const cm = competencies.reduce((m, c) => {
		m[ c.code ] = c._id;
		m[ c._id ] = c;
		if (!c.common) {
			competenciesIds.push(c._id);
		}
		return m;
	}, {});

	const disciplines = await db.disciplines.insert([
		{
			name: 'Философско-политологические и исторические аспекты военного управления',
			note: '',
			code: 'ОНД.01',
			cipher: 'ДМ-666',
			additional_complexity: false,
			part_type: 'basic',
			department_name: 'философии',
			competencies: [
				{
					_id: cm[ 'ОК-1' ],
					know: [
						'основные направления, формы и методы военно-социального управления в армиях государств мирового сообщества и в России',
						'военно-политические составляющие организации морально-психологического обеспечения Вооружённых Сил Российской Федерации',
						'политические аспекты управления морально-психологическим обеспечением служебно-боевой деятельности Вооруженных Сил Российской Федерации',
					],
					able_to: [
						'анализировать военную практику работы с личным составом в современных условиях',
						'руководствоваться социально-философскими, политологическими и историческими основами управленческой деятельности военных кадров',
					],
					own: [
						'навыком выделения главного в своей деятельности, способностью прогнозировать события, своевременно вносить изменения в принятые решения',
					],
				},
				{
					_id: cm[ 'ОК-2' ],
					know: [
						'особенности формирования и развития военных организаций, вооруженных сил в России и различных государствах мирового сообщества',
					],
					able_to: [
						'формировать духовный потенциал и нравственный облик военнослужащих, опираясь на гуманистические принципы нравственности',
					],
					own: [
						'навыками изучения и применения инновационных подходов в организационной культуре военного управления',
					],
				},
				{
					_id: cm[ 'ОК-3' ],
					know: [
						'историю становления и развития системы государственного и военного управления в России, характер и основные направления взаимодействия органов государственного и военного управления в условиях мирного и военного времени',
						'сущность, содержание понятия «национальные интересы Российской Федерации», механизм учета национальных интересов России в управленческой деятельности военных кадров',
					],
					able_to: [
						'оценивать и прогнозировать реальные перспективы и тенденции развития военной теории и практики с учетом философских, политологических и исторических аспектов',
					],
					own: [
						'навыками применения военно-гуманитарных знаний для формирования у подчинённых высоких морально-боевых качеств, чувства патриотизма и преданности Вооружённым Силам Российской Федерации, их оружию и традициям',
					],
				},
				{
					_id: cm[ 'ОПК-1' ],
					know: [
						'философско-методологические и политологические основы управленческой деятельности военных кадров',
						'место и роль военного управления в обеспечении национальной безопасности',
						'политические особенности военного управления в локальных войнах и вооруженных конфликтах, основные факторы, обеспечивающие их предотвращение и урегулирование',
					],
					able_to: [
						'анализировать события внутриполитической и международной жизни и грамотно использовать их в деятельности по поддержанию высокого уровня морально-психологического состояния подчиненного личного состава',
					],
					own: [
						'навыком принятия управленческих решений с учетом особенностей регулирования отношений в системе государственного и военного управления страны в современных условиях',
					],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 2,
						time: 2,
						teacher_time: 44,
						self_time: 28,
						exam: null,
						exam_time: null,
					}, {
						number: 3,
						time: 2,
						teacher_time: 44,
						self_time: 28,
						exam: 'credit_with_mark',
						exam_time: 27,
					},
				],
			},
		},
		{
			name: 'Правовое регулирование военного управления',
			note: '',
			code: 'ОНД.02',
			cipher: 'ДМ-148',
			additional_complexity: false,
			part_type: 'basic',
			department_name: 'права',
			competencies: [
				{
					_id: cm[ 'ОК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-5' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-8' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 2,
						teacher_time: 44,
						self_time: 28,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Организация работы с личным составом и управление морально-психологическим обеспечением войск (сил)',
			note: '',
			code: 'ОНД.03',
			cipher: 'ДМ-16',
			additional_complexity: false,
			part_type: 'basic',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ОК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-4' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-6' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 2,
						time: 2,
						teacher_time: 40,
						self_time: 32,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Иностранный язык',
			note: '',
			code: 'ОНД.04',
			cipher: 'ДМ-151',
			additional_complexity: false,
			part_type: 'basic',
			department_name: 'иностранного языка',
			competencies: [
				{
					_id: cm[ 'ОК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 2,
						teacher_time: 40,
						self_time: 32,
						exam: 'credit',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Теория военного управления',
			note: '',
			code: 'ОПД.01',
			cipher: 'ДМ-71',
			additional_complexity: false,
			part_type: 'basic',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ОПК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-15' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 5,
						teacher_time: 105,
						self_time: 75,
						exam: 'exam',
						exam_time: 36,
					},
				],
			},
		},
		{
			name: 'Основы теории военного искусства',
			note: '',
			code: 'ОПД.02',
			cipher: 'ДМ-14',
			additional_complexity: false,
			part_type: 'basic',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ОПК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 3,
						teacher_time: 72,
						self_time: 36,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'История военного искусства',
			note: '',
			code: 'ОПД.03',
			cipher: 'ДМ-32',
			additional_complexity: false,
			part_type: 'basic',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ОПК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 2,
						teacher_time: 45,
						self_time: 27,
						exam: 'credit_with_mark',
						exam_time: 18,
					},
				],
			},
		},
		{
			name: 'Оперативное искусство',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.01',
			cipher: 'ДМ-11',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ПК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-4' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 2,
						time: 1,
						teacher_time: 22,
						self_time: 14,
						exam: null,
						exam_time: null,
					},
					{
						number: 3,
						time: 5,
						teacher_time: 99,
						self_time: 81,
						exam: 'exam',
						exam_time: 36,
					},
				],
			},
		},
		{
			name: 'Тактика соединений ПВО, ГИК, ГИКЦ',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.02',
			cipher: 'ДМ-12',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'тактики',
			competencies: [
				{
					_id: cm[ 'ОПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-5' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-4' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-5' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-8' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 2,
						time: 3.5,
						teacher_time: 82,
						self_time: 44,
						exam: null,
						exam_time: null,
					},
					{
						number: 3,
						time: 3.5,
						teacher_time: 85,
						self_time: 41,
						exam: 'exam',
						exam_time: 36,
					},
				],
			},
		},
		{
			name: 'Оперативно-тактическое применение соединений ПРН, ПРО, РКО',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.03',
			cipher: 'ДМ-26',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'тактики',
			competencies: [
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 2,
						time: 2,
						teacher_time: 48,
						self_time: 24,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Тактика и оперативное искусство Сухопутных войск',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.04',
			cipher: 'ДМ-31',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-4' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-16' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 3,
						time: 3,
						teacher_time: 72,
						self_time: 36,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Боевое применение зенитных ракетных войск',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.05',
			cipher: 'ДМ-42',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ПК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-10' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-17' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 0.5,
						teacher_time: 12,
						self_time: 6,
						exam: null,
						exam_time: null,
					},
					{
						number: 2,
						time: 5.5,
						teacher_time: 109,
						self_time: 89,
						exam: 'exam',
						exam_time: 36,
					},
				],
			},
		},
		{
			name: 'Боевое применение радиотехнических войск',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.06',
			cipher: 'ДМ-62',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-17' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 1,
						teacher_time: 24,
						self_time: 12,
						exam: null,
						exam_time: null,
					},
					{
						number: 2,
						time: 1,
						teacher_time: 24,
						self_time: 12,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Боевое применение авиационных частей ВВС',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.07',
			cipher: 'ДМ-52',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-17' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 2,
						teacher_time: 46,
						self_time: 26,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Боевое применение АСУ и организация связи',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.08',
			cipher: 'ДМ-821',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ОПК-6' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-17' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 1.5,
						teacher_time: 36,
						self_time: 18,
						exam: null,
						exam_time: null,
					},
					{
						number: 2,
						time: 1.5,
						teacher_time: 36,
						self_time: 18,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Моделирование и оценка эффективности боевых действий',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.09',
			cipher: 'ДМ-121',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ОПК-6' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-7' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-13' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 2,
						teacher_time: 48,
						self_time: 24,
						exam: null,
						exam_time: null,
					},
					{
						number: 2,
						time: 1.5,
						teacher_time: 36,
						self_time: 18,
						exam: null,
						exam_time: null,
					},
					{
						number: 3,
						time: 0.5,
						teacher_time: 12,
						self_time: 6,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Разведка воздушно-космического противника и радиоэлектронная борьба',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.10',
			cipher: 'ДМ-94',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ВПК.ПК-16' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 1,
						teacher_time: 24,
						self_time: 12,
						exam: null,
						exam_time: null,
					},
					{
						number: 2,
						time: 0.5,
						teacher_time: 12,
						self_time: 6,
						exam: null,
						exam_time: null,
					},
					{
						number: 3,
						time: 0.5,
						teacher_time: 12,
						self_time: 6,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Маскировка и информационное противоборство',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.11',
			cipher: 'ДМ-15',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ОПК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-4' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-8' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-16' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 2,
						time: 1,
						teacher_time: 24,
						self_time: 12,
						exam: null,
						exam_time: null,
					},
					{
						number: 3,
						time: 1,
						teacher_time: 21,
						self_time: 15,
						exam: 'credit_with_mark',
						exam_time: 18,
					},
				],
			},
		},
		{
			name: 'Радиационная, химическая и биологическая защита и инженерное обеспечение',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.12',
			cipher: 'ДМ-101',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'РХБЗ',
			competencies: [
				{
					_id: cm[ 'ПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-4' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-16' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 0.5,
						teacher_time: 12,
						self_time: 6,
						exam: null,
						exam_time: null,
					},
					{
						number: 2,
						time: 1.5,
						teacher_time: 36,
						self_time: 18,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Материально-техническое и медицинское обеспечение ',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.13',
			cipher: 'ДМ-112',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-8' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-16' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 2,
						time: 1,
						teacher_time: 24,
						self_time: 12,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Защита государственной тайны',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.16',
			cipher: 'ДМ- 73',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ПК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-5' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-8' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-15' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 3,
						time: 1,
						teacher_time: 24,
						self_time: 12,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Управление повседневной деятельностью войск',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ВПД.14',
			cipher: 'ДМ-72',
			additional_complexity: false,
			part_type: 'variative',
			department_name: 'оперативного искусства',
			competencies: [
				{
					_id: cm[ 'ПК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-4' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-5' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-8' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-15' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 3,
						time: 1,
						teacher_time: 24,
						self_time: 12,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Физическая подготовка',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ФП.01',
			cipher: 'ДМ-161',
			additional_complexity: true,
			part_type: 'variative',
			department_name: 'физической подготовки',
			competencies: [
				{
					_id: cm[ 'ОК-4' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-15' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 1,
						teacher_time: 36,
						self_time: 0,
						exam: 'credit_with_mark',
						exam_time: null,
					},
					{
						number: 2,
						time: 1,
						teacher_time: 36,
						self_time: 0,
						exam: 'exam',
						exam_time: null,
					},
					{
						number: 3,
						time: 1,
						teacher_time: 36,
						self_time: 0,
						exam: 'credit_with_mark',
						exam_time: null,
					},
					{
						number: 4,
						time: 1,
						teacher_time: 36,
						self_time: 0,
						exam: 'exam',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Учебная практика',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'УП.01',
			cipher: '',
			additional_complexity: false,
			part_type: 'practice',
			department_name: '',
			competencies: [
				{
					_id: cm[ 'ПК-1' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-4' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-5' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-8' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-15' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-16' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 3.5,
						teacher_time: 88,
						self_time: 38,
						exam: null,
						exam_time: null,
					},
					{
						number: 2,
						time: 5.5,
						teacher_time: 140,
						self_time: 58,
						exam: null,
						exam_time: null,
					},
					{
						number: 3,
						time: 6.5,
						teacher_time: 160,
						self_time: 74,
						exam: null,
						exam_time: null,
					},
					{
						number: 4,
						time: 2.5,
						teacher_time: 60,
						self_time: 30,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Производственная практика',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ПП.01',
			cipher: '',
			additional_complexity: false,
			part_type: 'practice',
			department_name: '',
			competencies: [],
			direction_id,
			constraints: {
				semesters: [],
			},
		},
		{
			name: 'Войсковая стажировка',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ПП.01.1',
			cipher: '',
			additional_complexity: false,
			part_type: 'practice',
			department_name: '',
			competencies: [
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-15' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-18' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 4,
						time: 6,
						teacher_time: 160,
						self_time: 56,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Научно-исследовательская работа',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ПП.01.2',
			cipher: '',
			additional_complexity: false,
			part_type: 'practice',
			department_name: '',
			competencies: [
				{
					_id: cm[ 'ПК-7' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-11' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-12' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-13' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-18' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 1,
						time: 1,
						teacher_time: 24,
						self_time: 12,
						exam: null,
						exam_time: null,
					},
					{
						number: 2,
						time: 1,
						teacher_time: 24,
						self_time: 12,
						exam: null,
						exam_time: null,
					},
					{
						number: 3,
						time: 1.5,
						teacher_time: 36,
						self_time: 18,
						exam: null,
						exam_time: null,
					},
					{
						number: 4,
						time: 11.5,
						teacher_time: 276,
						self_time: 138,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Преддипломная практика',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: 'ПП.01.3',
			cipher: '',
			additional_complexity: false,
			part_type: 'practice',
			department_name: '',
			competencies: [
				{
					_id: cm[ 'ОК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-2' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-3' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ОПК-6' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-7' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-11' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-12' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ПК-13' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-18' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 4,
						time: 9,
						teacher_time: 216,
						self_time: 108,
						exam: 'credit_with_mark',
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Государственный междисциплинарный экзамен',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: '',
			cipher: '',
			additional_complexity: false,
			part_type: 'gia',
			department_name: '',
			competencies: [
				{
					_id: cm[ 'ВПК.ПК-14' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-15' ],
					know: [],
					able_to: [],
					own: [],
				},
				{
					_id: cm[ 'ВПК.ПК-16' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 4,
						time: 1.5,
						teacher_time: 0,
						self_time: 0,
						exam: null,
						exam_time: null,
					},
				],
			},
		},
		{
			name: 'Защита выпускной квалификационной работы',
			note: 'для специальности "Управление воинскими частями и соединениями ПВО"',
			code: '',
			cipher: '',
			additional_complexity: false,
			part_type: 'gia',
			department_name: '',
			competencies: [
				{
					_id: cm[ 'ВПК.ПК-18' ],
					know: [],
					able_to: [],
					own: [],
				},
			],
			direction_id,
			constraints: {
				semesters: [
					{
						number: 4,
						time: 4.5,
						teacher_time: 0,
						self_time: 0,
						exam: null,
						exam_time: null,
					},
				],
			},
		},
	]);

	const [ specialty ] = await db.specialties.insert([
		{
			name: 'Управление воинскими частями и соединениями ПВО',
			graduate_destinations: 'для прохождения службы в воинских частях, соединениях ПВО и объединениях ВКС на должностях: командир, заместитель командира (начальник штаба) воинской части ПВО, начальник, заместитель начальника, старший офицер отделения, отдела (оперативного, боевой подготовки, рода войск) соединения ПВО, объединения ВКС, воинские должности в научно-исследовательских учреждениях и образовательных организациях',
			approver: 'Врид заместителя начальника академии по учебной и научной работе полковник А.Гончаров',
			competencies: competenciesIds,
			disciplines: disciplines.filter(d => d.part_type === 'variative').map(d => d._id),
			direction_id,
		},
	]);

	console.dir(specialty);
})()
	.catch(console.error)
	.then(() => console.log('Done'));
